### ISSUE TITLE
running pyinfra from windows error when trying to run a simple 'echo' command

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#253]
Got errors running pyinfra from windows.

Is running pyinfra windows supported?

Here's the info:

```
(venv) PS C:\Users\vagrant> pyinfra.exe --user vagrant --password vagrant "192.168.2.232" --port 22 exec -- echo hello
'stty' is not recognized as an internal or external command,
operable program or batch file.
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\host.py", line 82, in connect
    self.connection = self.executor.connect(state, self, *args, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\ssh.py", line 162, in connect
    client.connect(hostname, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 36, in connect
    self.hostname, self.config = self.parse_config(hostname)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 51, in parse_config
    host_config = ssh_config.lookup(hostname)
AttributeError: 'NoneType' object has no attribute 'lookup'
2020-01-20T21:20:33Z <Greenlet at 0x2522aca6ae0: <bound method Host.connect of 192.168.2.232>(<pyinfra.api.state.State object at 0x000002522AD79)> failed with AttributeError

--> [31m[1mAn unexpected exception occurred[0m:

  File "c:\users\vagrant\venv\lib\site-packages\gevent\_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)

--> The full traceback has been written to [1mpyinfra-debug.log[0m
(venv) PS C:\Users\vagrant> cat .\pyinfra-debug.log
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra_cli\main.py", line 195, in main
    _main(*args, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra_cli\main.py", line 434, in _main
    connect_all(state)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connect.py", line 35, in connect_all
    greenlet.get()
  File "src/gevent/greenlet.py", line 683, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "src/gevent/greenlet.py", line 496, in gevent._greenlet.Greenlet.exc_info.__get__
  File "c:\users\vagrant\venv\lib\site-packages\gevent\_tblib.py", line 371, in g
    return f(a)
  File "c:\users\vagrant\venv\lib\site-packages\gevent\_tblib.py", line 432, in load_traceback
    return loads(s)
  File "c:\users\vagrant\venv\lib\site-packages\gevent\_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "c:\users\vagrant\venv\lib\site-packages\gevent\_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
(venv) PS C:\Users\vagrant>
```

Note that I used the steps from https://github.com/Fizzadar/pyinfra/pull/237/commits/964c14405fcdd22c53aaf50f7f09f4dc5e554d13 to test this with.

I've tried using the ip address with single quotes and no quotes, too. Same results.

I've also tried adding line in C:\Windows\System32\drivers\etc\hosts but I get same error.

**Comment by mkinney** [comment]
Hmm... might be python3.8 issue. Will try python3.7.

See https://github.com/gevent/gevent/issues/1491

**Comment by mkinney** [comment]
Does not work using python 3.7 either:

```
(venv) PS C:\Users\vagrant> pyinfra --user vagrant --password vagrant 192.168.2.232 exec -- echo hello
'stty' is not recognized as an internal or external command,
operable program or batch file.
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\host.py", line 82, in connect
    self.connection = self.executor.connect(state, self, *args, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\ssh.py", line 162, in connect
    client.connect(hostname, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 36, in connect
    self.hostname, self.config = self.parse_config(hostname)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 51, in parse_config
    host_config = ssh_config.lookup(hostname)
AttributeError: 'NoneType' object has no attribute 'lookup'
2020-01-20T22:13:07Z <Greenlet at 0x29f710f7268: <bound method Host.connect of 192.168.2.232>(<pyinfra.api.state.State object at 0x0000029F6FDA9)> failed with AttributeError

--> [31m[1mAn unexpected exception occurred[0m:

  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 51, in parse_config
    host_config = ssh_config.lookup(hostname)
AttributeError: 'NoneType' object has no attribute 'lookup'

--> The full traceback has been written to [1mpyinfra-debug.log[0m
(venv) PS C:\Users\vagrant> type .\pyinfra-debug.log
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra_cli\main.py", line 195, in main
    _main(*args, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra_cli\main.py", line 434, in _main
    connect_all(state)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connect.py", line 35, in connect_all
    greenlet.get()
  File "src\gevent\greenlet.py", line 683, in gevent._greenlet.Greenlet.get
  File "src\gevent\greenlet.py", line 317, in gevent._greenlet.Greenlet._raise_exception
  File "c:\users\vagrant\venv\lib\site-packages\gevent\_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\host.py", line 82, in connect
    self.connection = self.executor.connect(state, self, *args, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\ssh.py", line 162, in connect
    client.connect(hostname, **kwargs)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 36, in connect
    self.hostname, self.config = self.parse_config(hostname)
  File "c:\users\vagrant\venv\lib\site-packages\pyinfra\api\connectors\sshuserclient\client.py", line 51, in parse_config
    host_config = ssh_config.lookup(hostname)
AttributeError: 'NoneType' object has no attribute 'lookup'
```

**Comment by mkinney** [comment]
Cool. If you use python 3.7 on windows you do not need to install visual studio to install pyinfra.

**Comment by Fizzadar** [comment]
This should now be fixed by https://github.com/Fizzadar/pyinfra/commit/01ee3100ea8bcc8e722ac51ce24cfb3fc9f9e4bb.

**Comment by mkinney** [comment]
Thanks.

This would be hard to test until a new version of pyinfra is released, right?

**Comment by Fizzadar** [comment]
Yep - I'm planning on releasing `v0.13` tonight.
